# Generated by Django 4.2.17 on 2025-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_headernav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headernav',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
