# Generated by Django 4.2.17 on 2025-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_headernav_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('img', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='headernav',
            name='img',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
