# Generated by Django 4.2.17 on 2025-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=500)),
                ('btn', models.CharField(max_length=500)),
                ('img', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
