# Generated by Django 4.2.17 on 2025-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='btn',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
